export const HANDLE_USER_ROLE = "/USER/HANDEL_USER_ROLE";
export const HANDLE_USER_ACCOUNT = "/USER/HANDLE_USER_ACCOUNT";
export const HANDLE_USER_PASSWORD = "/USER/HANDLE_USER_PASSWORD";
export const HANDLE_USER_SUBMIT = "/USER/HANDLE_USER_SUBMIT";